### Algebra: Quantum Mechanics

Reference: http://qutip.org/docs/latest/index.html

In [81]:
import numpy as np
from qutip import *
import seaborn as sns
import matplotlib.pyplot as plt
import numpy.linalg as LA
from scipy.linalg import expm
%matplotlib inline
sns.set()

In [3]:
#!pip install qutip

#### 1. Hydrogen Atom: Angular Momentum

![img](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTRMh9_FL09_N_ftKHwlFvsrwyJQv_wgu_hVg&usqp=CAU)

$\psi(x) = \langle x|\psi \rangle$; $\phi(p) = \langle p|\phi \rangle$

$Y_{l,m} = \langle \theta,\phi|l,m \rangle$

----------

####  Experiment1 : Spin Angular Momentum $s = 1/2, ms = -1/2, 1/2$
Matrix size = 2x2

In [86]:
sx = np.array(sigmaz())
sy = np.array(sigmax())
sz = np.array(sigmay())
sx,sy,sz

(array([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]]), array([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]]), array([[0.+0.j, 0.-1.j],
        [0.+1.j, 0.+0.j]]))

In [87]:
s_square = (np.dot(sx,sx) + np.dot(sy,sy) +np.dot(sz,sz))
s_square

array([[3.+0.j, 0.+0.j],
       [0.+0.j, 3.+0.j]])

- Rotation $ R(\theta) = e^{-i \theta n.\sigma} = e^{-i (\theta_x \sigma_x + \theta_y \sigma_y + \theta_z \sigma_z)} $

In [88]:
Rx = expm(-1j*np.pi/12*sx)
Ry = expm(-1j*np.pi/10*sy)
Rz = expm(-1j*np.pi/8*sz)
Rz,Rx,Ry

(array([[ 0.92387953+0.j, -0.38268343+0.j],
        [ 0.38268343+0.j,  0.92387953+0.j]]),
 array([[0.96592583-0.25881905j, 0.        +0.j        ],
        [0.        +0.j        , 0.96592583+0.25881905j]]),
 array([[0.95105652+0.j        , 0.        -0.30901699j],
        [0.        -0.30901699j, 0.95105652+0.j        ]]))

In [89]:
R = np.dot(Rx,np.dot(Ry,Rz))
R

array([[ 0.81811516-0.34164059j, -0.42544356-0.18156837j],
       [ 0.42544356-0.18156837j,  0.81811516+0.34164059j]])

In [90]:
LA.det(R)

(1.0000000000000004+0j)

#### Experiment 2 : Angular Momentum $l =1, m = -1,0,1$
Matrix size  = 3x3

In [7]:
jmat(1)

(Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[0.         0.70710678 0.        ]
  [0.70710678 0.         0.70710678]
  [0.         0.70710678 0.        ]],
 Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[0.+0.j         0.-0.70710678j 0.+0.j        ]
  [0.+0.70710678j 0.+0.j         0.-0.70710678j]
  [0.+0.j         0.+0.70710678j 0.+0.j        ]],
 Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
 Qobj data =
 [[ 1.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0. -1.]])

In [99]:
LX = np.array(jmat(1,'x'))
LY = np.array(jmat(1,'y'))
LZ = np.array(jmat(1,'z'))

In [100]:
np.dot(LX,LY) == np.dot(LY,LX)

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [101]:
L_square = (np.dot(LX,LX) + np.dot(LY,LY) +np.dot(LZ,LZ))
L_square

array([[2.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 2.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 2.+0.j]])

- Rotaion $ R(\theta) = e^{-i \theta n.L} = e^{-i (\theta_x L_x + \theta_y L_y + \theta_z L_z)} $

In [109]:
Rx = expm(-(0.+1.0j)*0.1*LX)
Ry = expm(-(0.+1.0j)*0.2*LY)
Rz = expm(-(0.+1.0j)*0.3*LZ)
Rx,Ry,Rz

(array([[ 0.99750208+0.j        ,  0.        -0.07059289j,
         -0.00249792+0.j        ],
        [ 0.        -0.07059289j,  0.99500417+0.j        ,
          0.        -0.07059289j],
        [-0.00249792+0.j        ,  0.        -0.07059289j,
          0.99750208+0.j        ]]),
 array([[ 0.99003329+0.j, -0.14048043+0.j,  0.00996671+0.j],
        [ 0.14048043+0.j,  0.98006658+0.j, -0.14048043+0.j],
        [ 0.00996671+0.j,  0.14048043+0.j,  0.99003329+0.j]]),
 array([[0.95533649-0.29552021j, 0.        +0.j        ,
         0.        +0.j        ],
        [0.        +0.j        , 1.        +0.j        ,
         0.        +0.j        ],
        [0.        +0.j        , 0.        +0.j        ,
         0.95533649+0.29552021j]]))

In [110]:
R = np.dot(Rx,np.dot(Ry,Rz))
R

array([[ 0.94049792-3.01310652e-01j, -0.14048043-6.91857281e-02j,
         0.00420456+1.16811741e-02j],
       [ 0.11267399-1.08747365e-01j,  0.97517033+6.69983947e-18j,
        -0.11267399-1.08747365e-01j],
       [ 0.00420456-1.16811741e-02j,  0.14048043-6.91857281e-02j,
         0.94049792+3.01310652e-01j]])

In [111]:
LA.det(R)

(0.9999999999999997+0j)

In [112]:
R_xy = np.dot(Rx,Ry)
R_yx = np.dot(Ry,Rx)

In [116]:
R_xy==R_yx

array([[False, False, False],
       [False, False, False],
       [ True, False, False]])

#### Experiment 3 : Angular Momentum plus Spin $l = 3/2, m = -3/2,-1/2,1/2,3/2$
Matrix size = 4x4

In [48]:
jmat(3/2,'x')

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.        0.8660254 0.        0.       ]
 [0.8660254 0.        1.        0.       ]
 [0.        1.        0.        0.8660254]
 [0.        0.        0.8660254 0.       ]]

In [49]:
jmat(3/2,'y')

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j        0.-0.8660254j 0.+0.j        0.+0.j       ]
 [0.+0.8660254j 0.+0.j        0.-1.j        0.+0.j       ]
 [0.+0.j        0.+1.j        0.+0.j        0.-0.8660254j]
 [0.+0.j        0.+0.j        0.+0.8660254j 0.+0.j       ]]

#### Summary: Structure of a general rotation matrix (R) in Hilbert space
j = 1/2,1,3/2,2,5/2,3,...

- A general rotation matrix ($R$) in hilbert space of basis $|l,m\rangle$ appears as block diagonal matrix, wher every block represents the rotation with specific subspaces called irriducible subspace.
- In the same basis $|l,m\rangle$  Hamiltonian Matrix $H$, $J^2$ and $J_z$ are simultaneously diagonalized.

![img](https://physicscourses.colorado.edu/phys5250/phys5250_fa19/images/block-diag.png)

-----------

#### 2. Quantum Harmonic Oscillator

In [8]:
momentum(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.+0.j         0.-0.70710678j 0.+0.j         0.+0.j
  0.+0.j        ]
 [0.+0.70710678j 0.+0.j         0.-1.j         0.+0.j
  0.+0.j        ]
 [0.+0.j         0.+1.j         0.+0.j         0.-1.22474487j
  0.+0.j        ]
 [0.+0.j         0.+0.j         0.+1.22474487j 0.+0.j
  0.-1.41421356j]
 [0.+0.j         0.+0.j         0.+0.j         0.+1.41421356j
  0.+0.j        ]]

In [9]:
position(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.         0.70710678 0.         0.         0.        ]
 [0.70710678 0.         1.         0.         0.        ]
 [0.         1.         0.         1.22474487 0.        ]
 [0.         0.         1.22474487 0.         1.41421356]
 [0.         0.         0.         1.41421356 0.        ]]

In [10]:
create(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [11]:
destroy(5)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]

In [12]:
num(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]]

#### 3. Random Matrices

- Random hermitian matrix

In [59]:
rand_herm(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-0.50113582+0.j         -0.17222998+0.14571042j  0.        +0.j
  -0.06039662+0.6965142j ]
 [-0.17222998-0.14571042j  0.1689534 +0.j         -0.30474969+0.58835929j
   0.04412378+0.64077284j]
 [ 0.        +0.j         -0.30474969-0.58835929j  0.        +0.j
  -0.45812567-0.08748371j]
 [-0.06039662-0.6965142j   0.04412378-0.64077284j -0.45812567+0.08748371j
   0.75578241+0.j        ]]

- Random Unitary Matrix

In [56]:
rand_unitary(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 3.32426091e-01-0.61008781j -2.48216764e-01+0.00742287j
  -3.32218003e-01-0.26721645j  4.67803649e-01-0.23453233j]
 [-6.18056368e-02-0.08520346j  8.37959790e-01-0.35291461j
  -3.11514724e-01-0.25291069j  3.58896057e-05-0.03449434j]
 [-3.17360027e-02-0.48099205j  1.44640852e-01-0.29316018j
   7.90378747e-01+0.10591817j  2.00616601e-02-0.15638388j]
 [-4.27155409e-01+0.30229774j  6.86551818e-02+0.00553252j
   1.09189564e-01+0.0968594j   8.34155661e-01-0.06550129j]]

### Reference
1. [Rotation](https://www2.ph.ed.ac.uk/~ldeldebb/docs/QM2/chap4.pdf)